tasks/tasks/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks1/', include('tasks1.urls'))
]

tasks/tasks1/urls.py
from django.urls import path
from . import views

app_name = 'tasks1'
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

tasks/tasks1/models.py
from django.db import models

# Create your models here.

tasks/tasks1/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    priority = forms.IntegerField(label="Priority", min_value=1, max_value=10)
# Create your views here.

def index(request):
    if "tasks" not in request.session:
        request.session["tasks"]=[]
    tasks=request.session["tasks"]
    tasks.sort(key = lambda x: x[1],reverse=True)
    #task_list=[x[0] for x in tasks]
    return render(request, "tasks1/index.html",{
        "tasks":tasks
    })

def add(request):
    if request.method == 'POST':
        form = NewTaskForm(request.POST)
        if form.is_valid():
            new_task=form.cleaned_data["task"]
            new_priority=form.cleaned_data["priority"]
            new_tuple=(new_task,new_priority)
            request.session["tasks"] += [new_tuple]
	#redirect to tasks page
            return HttpResponseRedirect(reverse("tasks1:index"))
        else:
	#return the invalid form back
            return render(request, "tasks1/add.html", {
            "form": form
            })
	#return empty form request method is not post
    return render(request, "tasks1/add.html", {
        "form": NewTaskForm()
    })

tasks/tasks1/templates/tasks1/add.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Add Task</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    
    <body>
        <h1>Add Task</h1>
        <form action="{% url 'tasks1:add' %}", method="post">
            {% csrf_token %}
            {{ form }}

            <input type="submit" class="btn btn-warning" value="Submit" > 
        </form>
        <a href="{% url 'tasks1:index' %}">See tasks</a>
    </body>
</html>

tasks/tasks1/templates/tasks1/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
	h1 {
		padding-left:40px;}

	a{
		padding-left:40px;
    </style>
</head>
<body>
    <h1>Tasks</h1>
    <ul>
        {% for task in tasks %}
        {% if task.1 > 8 %}
         <li class="list-group-item list-group-item-danger">
          {{task.0}}

          <strong style="float:right; margin-right:50px "> {{"Urgent!"}}</strong>
	  </li>

        {% else %}
        <li class="list-group-item list-group-item-info">
           {{ task.0 }}

        </li>
        {% endif %}
	{% empty %}
            <li>No tasks.</li>
        {% endfor %}
    </ul>

       <a href="{% url 'tasks1:add' %}">Add a new task</a>

</body>
</html>